# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLYYi8cyxgAD_eNaugFj-WN8o3DUZySb

I use the extended version of the dataset because it includes weekly study hours, which is the main variable in this project.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("Expanded_data_with_more_features.csv")

df = df.fillna(df.mode().iloc[0])

df['exam_score'] = (df['MathScore'] + df['ReadingScore'] + df['WritingScore']) / 3

sns.countplot(x='WklyStudyHours', data=df, order=['< 5','5 - 10','> 10'])
plt.title("Distribution of Weekly Study Hours")
plt.show()

df.info()
df.isnull().sum()
df = df.fillna(df.mode().iloc[0])
df.isnull().sum()

df["exam_score"] = (df["MathScore"] + df["ReadingScore"] + df["WritingScore"]) / 3
df[["MathScore", "ReadingScore", "WritingScore", "exam_score"]].head()
df[["MathScore", "ReadingScore", "WritingScore", "exam_score"]].describe()

"""I created an average exam score variable to represent overall academic performance instead of looking at three separate scores every time."""

sns.countplot(x="WklyStudyHours", data=df, order=["< 5", "5 - 10", "> 10"])
plt.title("Distribution of Weekly Study Hours")
plt.xlabel("Weekly Study Hours")
plt.ylabel("Count")
plt.show()

sns.histplot(df["exam_score"], kde=True)
plt.title("Distribution of Average Exam Score")
plt.xlabel("Average Exam Score")
plt.ylabel("Frequency")
plt.show()

sns.boxplot(x="WklyStudyHours", y="exam_score", data=df, order=["< 5", "5 - 10", "> 10"])
plt.title("Weekly Study Hours and Exam Score")
plt.xlabel("Weekly Study Hours")
plt.ylabel("Average Exam Score")
plt.show()

"""Students in higher study-hour groups generally have higher exam scores, there is still a visible positive relationship!!!!!!!!!THIS PART IS THE MOST IMPORTANT PART FOR OUR PROJECT"""

sns.boxplot(x="TestPrep", y="exam_score", data=df)
plt.title("Test Preparation and Exam Score")
plt.xlabel("Test Preparation")
plt.ylabel("Average Exam Score")
plt.show()

"""Students who completed the test preparation course seem to score higher on average. This suggests that study time may not be the only factor related to performance.This part is extra for project."""

plt.figure(figsize=(10,5))
sns.boxplot(x="ParentEduc", y="exam_score", data=df)
plt.title("Parental Education and Exam Score")
plt.xlabel("Parental Education")
plt.ylabel("Average Exam Score")
plt.xticks(rotation=45)
plt.show()

"""There also seems to be some variation in exam scores across parental education levels, so background factors may also matter.This part is extra for project.

STATISTICAL TESTING
"""

study_map = {"< 5": 1, "5 - 10": 2, "> 10": 3}
df["study_num"] = df["WklyStudyHours"].map(study_map)

df[["WklyStudyHours", "study_num"]].head()

"""Since weekly study hours are stored as categories, I converted them into ordered numeric values for statistical testing."""



"""H0: There is no relationship between weekly study time and average exam score.

H1: There is a relationship between weekly study time and average exam score.
"""

from scipy.stats import pearsonr
corr, p_value = pearsonr(df["study_num"], df["exam_score"])
print("Correlation:", corr)
print("P-value:", p_value)

"""**Since p_value < 0.05:**
The p-value is below 0.05, so the null hypothesis is rejected. This means there is a statistically significant relationship between weekly study time and average exam score.
The correlation between study time and exam score is positive but very weak. Although the p-value is extremely small, indicating statistical significance, the strength of the relationship is quite low. This suggests that study time alone is not a strong predictor of academic performance.

Based on the analysis, there is a statistically significant relationship between weekly study time and exam scores. However, the correlation coefficient is extremely low, indicating that this relationship is very weak.
Overall, it can be observed that students who spend more time studying tend to perform slightly better in exams on average. Still, the relationship is not perfectly straightforward, and after a certain point, studying more may not lead to equally strong improvements.
It is also clear that other factors, such as test preparation, prior knowledge, and family background, play an important role in academic performance. Therefore, study time alone is not enough to fully explain student success.
In general, study time is a relevant factor, but it should be evaluated together with other variables to better understand academic outcomes.
"""

